name: sliver_fill_remaining_box_adapter
description: Flutter package providing SliverFillRemainingBoxAdapter, a sliver that fills the remaining space or shows its child, whichever is larger.
version: 0.0.1
author: Morgan McKenzie <rmtmckenzie@gmail.com>
homepage: https://github.com/rmtmckenzie/flutter_sliver_fill_remaining_box_adapter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter